yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from posts import views


app_name = 'group_list'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('profile/<str:username>/', views.profile, name='profile'),
]

yatube/users/urls.py
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeDoneView, PasswordChangeView,
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView,
    PasswordResetCompleteView)
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path('password_change/',
         PasswordChangeView.as_view(
             template_name='users/password_change_form.html'),
         name='password_change'
         ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from posts import views


urlpatterns = [
    path('', views.index, name='index'),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models


User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        out_text: str = f'{self.title}'
        return (out_text)


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Текст поста'
    )
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts')
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост')

    def __str__(self):
        return self.text

    class Meta:
        ordering = ['-pub_date']

yatube/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')
        labels = ('Текст поста', 'Группа')

yatube/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


User = get_user_model()


#  создадим собственный класс для формы регистрации
#  сделаем его наследником предустановленного класса UserCreationForm
class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        # укажем модель, с которой связана создаваемая форма
        model = User
        # укажем, какие поля должны быть видны в форме и в каком порядке
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Здесь можно произвести какие-то действия для создания контекста.
        # Для примера в словарь просто передаются две строки
        context['just_title'] = 'Очень простая страница'
        context['just_text'] = ('На создание этой страницы '
                                'у меня ушло пять минут! Ай да я.')
        return context


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from .forms import PostForm
from .models import Post, Group, User
from .utils import mypaginator


def index(request):
    post_list = Post.objects.select_related('group')
    page_obj = mypaginator(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = Post.objects.select_related('group').filter(group=group)
    page_obj = mypaginator(request, post_list)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = Post.objects.select_related('group').filter(author=author)
    post_count = post_list.count()
    page_obj = mypaginator(request, post_list)
    context = {
        'author': author,
        'page_obj': page_obj,
        'post_count': post_count,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    context = {
        'post': post,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', request.user)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)
    form = PostForm(request.POST or None, instance=post)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:post_detail', post_id)
    return render(request, 'posts/create_post.html',
                  {'form': form, 'post_id': post_id, 'is_edit': True})

yatube/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView
from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    # После успешной регистрации перенаправляем пользователя на главную.
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends "base.html" %}
{% load static %}  
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<div class="row">
  <h1>Привет, я Дмитрий</h1>
   <aside class="col-12 col-md-3">
    <p> 
      Я начал программировать в 1987 году в ВУЗе как любитель, а в 1991 году начал работать программистом.
      До 2011 года я проектировал, разрабатывал и внедрял различные банковские (и не только) приложения.
      Потом был перерыв 11 лет. 
      <a href="https://tula.hh.ru/resume/65ccfb13ff0942cdd40039ed1f576b516d6436">Сейчас хочу вернуться в программирование </a>
      и получаю огромное удовольствие от 
      <a href="https://github.com/Dnevvs">этого </a>
      и от обучения на Яндекс.Практикуме.
    </p>
    <p>
        Пока у меня очень слабо с версткой страниц, поэтому ... 
      </p>
      <img src="{% static 'auth1.png' %}" width="200" height="300"
      class="d-inline-block align-top" alt="">
   </aside>
</div>
{% endblock %} 

yatube/templates/about/tech.html
{% extends "base.html" %}
{% load static %}
{% block title %}Технологии{% endblock %}
{% block content %}
{% comment %} Колонки с отступом сверху и снизу {% endcomment %}
<div class="row">
  <h1>Вот что я умею</h1>
  {% comment %}
    Боковой блок со списком технологий 
    Займет всю ширину блока на мобильном
    и 25% при размерах экрана ≥768px
  {% endcomment %}
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <img src="{% static 'tech1.png' %}" class="d-inline-block align-top" alt="">
      <li class="list-group-item">
        Python
        <img src="{% static 'tech2.png' %}"  >
      </li>
      <li class="list-group-item">
        Django
        <img src="{% static 'tech3.png' %}"  >
      </li>
      <li class="list-group-item">
        SQL <img src="{% static 'tech4.png' %}"  >
      </li>
      <li class="list-group-item">
        HTML
        <img src="{% static 'tech6.png' %}"  width="50" height="50"
        class="d-inline-block align-top" alt="">
        <img src="{% static 'tech5.png' %}"  >
      </li>
    </ul>
  </aside>
  {% comment %}
    Статья  
    Займет всю ширину блока на мобильном
    и 75% при размерах экрана ≥768px
  
  <article class="col-12 col-md-9">
    <p>Текст страницы "Технологии"
       
       На этой странице можно рассказать, 
       какие программные инструменты вы применили 
       для создания этого сайта, какие навыки вам
       помогли, с чем вы хорошо разобрались, 
       а с чем — не очень. 
       
       Картинки и нестандартные подходы приветствуются: 
       эта страница может получиться очень интересной.
    </p>
  </article>
  {% endcomment %}
</div>
{% endblock %} 

yatube/templates/base.html
<!DOCTYPE html> 
<html lang="ru">
  {% load static %}   
  <head>    
    <meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head> 
  {% include 'includes/header.html' %}
  <title>
    {% block title %}
      Контент не подвезли :(
    {% endblock %}
  </title>
  <h1>
    {% block header %}
    {% endblock %}
  </h1>
  <body>
    <main>
      {% block content %}
        Контент не подвезли :(
      {% endblock %}
    </main>
  </body>
  {% include 'includes/footer.html' %} 
</html>

yatube/templates/includes/footer.html
<!DOCTYPE html>
<footer class="page-footer font-small blue border-top">
    <div class="footer-copyright text-center py-3">© {{ year }} Copyright 
      <p><span style="color:red">Ya</span>tube</p> 
    </div>    
</footer>

yatube/templates/includes/header.html
<!DOCTYPE html>  
{% load static %}  
{% with request.resolver_match.view_name as view_name %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      <ul class="nav nav-pills">
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}"
           href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}" 
          href="{% url 'about:tech' %}">Технологии</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}"
           href="{% url 'posts:post_create' %}">Новая запись</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'users:password_change' %}active{% endif %}"
           href="{% url 'users:password_change' %}">Изменить пароль</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'users:logout' %}active{% endif %}" 
          href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li>
          Пользователь: {{ user.username }}
        </li>
        {% else %}
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'users:login' %}active{% endif %}" 
          href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'users:signup' %}active{% endif %}" 
          href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>      
</header> 
{% endwith %} 

yatube/templates/posts/create_post.html
<!DOCTYPE html> 
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %}
      Редактировать запись
    {% else %}
      Добавить запись
    {% endif %}
{% endblock %}
{% block content %}
{% load user_filters %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                {% if is_edit %}
                  Редактировать запись
                {% else %}
                  Добавить запись
                {% endif %}
              </div>
              <div class="card-body">    
                {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
                {% endif %}    
                <form method="post" action="{% if is_edit %}{% url 'posts:post_edit' post_id %}
                {% else %}{% url 'posts:post_create' %}{% endif %}">
                  {% csrf_token %}
                  {% for field in form %}
                    <div class="form-group row my-3 p-3">
                      <label for="{{ field.id_for_label }}">
                        {{ field.label }} 
                          {% if field.field.required %}
                            <span class="required text-danger" >*</span> 
                        {% endif %}
                      </label>
                      {{ field|addclass:"form-control" }}
                        {% if field.help_text %}
                          <small 
                              id="{{ field.id_for_label }}-help" 
                              class="form-text text-muted"
                          >
                            {{ field.help_text|safe }}
                          </small>
                        {% endif %}
                    </div>
                  {% endfor %}
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %} 
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
  {% endblock %}

yatube/templates/posts/group_list.html
<!DOCTYPE html> 
{% extends 'base.html' %}
{% block title %}
  {{ group.title }}
{% endblock %}
{% block header %}
  {{ group.title }}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <p>{{ group.description }}</p>
    {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>{{ post.text }}</p>
        <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
        </article>    
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %} 
    {% include 'posts/includes/paginator.html' %}
  </div>  
{% endblock %}

yatube/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/index.html
<!DOCTYPE html> 
{% extends 'base.html' %}
{% block title %}
  Последние обновления на сайте
{% endblock %}
{% block header %}
  Последние обновления на сайте
{% endblock %}
{% block content %}
  <div class="container py-5">     
    {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>{{ post.text }}</p>
        {% if post.group %}   
          <a 
            href="{% url 'posts:group_list' post.group.slug %}">все записи группы
          </a>
        {% endif %}
      </article>    
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %} 
    {% include 'posts/includes/paginator.html' %}
  </div>  
{% endblock %}

yatube/templates/posts/post_detail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block title %}
    Пост   {{ post.text|truncatechars:30 }}
{% endblock %}
{% block content %}
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li>
            {% if post.group %}   
                <li class="list-group-item">
                    Группа: {{ post.group.title }}
                <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы
                </a>
            {% endif %}
            </li>
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ post.author.posts.count }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          <p>
            {{ post.text }}
          </p>
          {% if request.user == post.author %}
            <a href="{% url 'posts:post_edit' post.id %}">редактировать запись</a>
          {% endif %}
        </article>
      </div> 
{% endblock %}

yatube/templates/posts/profile.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block title %}
    Профайл пользователя {{ author.get_full_name }}
{% endblock %}
{% block header %}
    Все посты пользователя {{ author.get_full_name }}
{% endblock %}
{% block content %}
    <div class="container py-5">   
        <h3>Всего постов: {{ post_count }} </h3>   
        {% for post in page_obj %}
            <article>
              <ul>
                <li>
                    Автор: {{ post.author.get_full_name }}
                    <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
                </li>
                <li>
                  Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
              </ul>
              <p>{{ post.text }}</p>
              <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
              
            {% if post.group %}   
                <li class="list-group-item">
                    Группа: {{ post.group.title }}
                <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            {% endif %}
            </article>  
            {% if not forloop.last %}<hr>{% endif %}
        {% endfor %} 
        {% include 'posts/includes/paginator.html' %}     
    </div>
{% endblock %}

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}
  Вы вышли из системы
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Выход
        </div>
        <div class="card-body">
          <p>
            Вы вышли из своей учётной записи. Ждём вас снова!
          </p>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
{% endblock %} 

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}
  Войти
{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}
          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}
          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
            <label for="{{ field.id_for_label }}">
              {{ field.label }}
                {% if field.field.required %}
                  <span class="required text-danger">*</span>
                {% endif %}
            </label>
          <div>
          {{ field|addclass:'form-control' }}
            {% if field.help_text %}
              <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                {{ field.help_text|safe }}
              </small>
            {% endif %}
          </div>
          </div>
            {% endfor %}
          <div class="col-md-6 offset-md-4">
          <button type="submit" class="btn btn-primary">
              Войти
          </button>
          <a href="{% url 'users:password_reset' %}" class="btn btn-link">
            Забыли пароль?
          </a>
        </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
{% endblock %} 

yatube/templates/users/password_change_done.html
{% extends "base.html" %}
{% block title %}
	Пароль изменён
{% endblock %}
{% block content %}
	{% load user_filters %}
	<div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Пароль изменён
              </div>
              <div class="card-body"> 
                <p>Пароль изменён успешно</p>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
    </div>
{% endblock %}

yatube/templates/users/password_change_form.html
{% extends "base.html" %}
{% block title %}
	Изменение пароля	
{% endblock %}
{% block content %}
	{% load user_filters %}
	<div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Изменить пароль
              </div>
              <div class="card-body">
                <form method="post" 
                {% if action_url %}
                   action="{% url 'users:password_change_done' %}"
                {% endif %}
                >
                  {% csrf_token %}
                  <div class="form-group row my-3 p-3">
                    <label for="id_old_password">
                      Старый пароль
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="old_password" autofocus class="form-control" required id="id_old_password">
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password1">
                      Новый пароль
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
                      <small id="id_new_password1-help" class="form-text text-muted">
                        <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                      </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password2">
                      Подтверждение нового пароля
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Изменить пароль
                    </button>
                  </div>
                </form>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
      </div>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}
  Зарегистрироваться
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
            {% load user_filters %} {# Загружаем фильтры #}
              {% if form.errors %}
                {% for field in form %} 
                  {% for error in field.errors %}            
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
            {% endif %}
            <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}

            {# Выводим поля в цикле, по отдельности #}
            {% for field in form %} 
              <div class="form-group row my-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                </label>
                {# К полю ввода добавляем атрибут class #}
                {{ field|addclass:'form-control' }} 
                {% if field.help_text %}
                  <small 
                    id="{{ field.id_for_label }}-help"
                    class="form-text text-muted"
                  >
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            {% endfor %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Зарегистрироваться
              </button>
            </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
{% endblock %} 